const express = require('express');
const connectDB= require('./config/db');
const bodyParser= require ('body-parser');
const dotenv= require('dotenv');
dotenv.config();
const app= express();
connectDB();
app.use(bodyParser.json());
app.use('/api/auth', require('./routes/auth'));
app.use('/api/categories', require('./routes/categories'));
app.use('/api/tasks', require('./routes/tasks'));
const PORT = process.env.PORT || 5000;
app.listen(PORT,()=> console.log('server started on port ${PORT}'));